### ISSUE TITLE
CasparCG Module - Failed to play clips in subfolder

### ISSUE THREAD

**Issue by didikunz** [bitfocus/companion-module-casparcg#5]
When a clip is in a sub-folder of Caspars Media folder the backslash character needs to be escaped properly, see [here](https://github.com/CasparCG/help/wiki/AMCP-Protocol#special-sequences) That happens in Windows, I don't know if there is any difference in handling these things in other operatin systems.

**Comment by haakonnessjoen** [comment]
Weird that they don't add the backslash themselves when listing mediafiles to us..

**Comment by haakonnessjoen** [comment]
Please test in current lastest build of companion. (should be ready on bitfocus.io in about 5 minutes)

**Comment by didikunz** [comment]
> Please test in current lastest build of companion. (should be ready on bitfocus.io in about 5 minutes)
I only find the last release from September. Is there a download link for the last build?

**Comment by haakonnessjoen** [comment]
![image](https://user-images.githubusercontent.com/416667/70707978-c19d1680-1cd9-11ea-88a6-e47bcab62942.png)
Click on the "Builds" link under companion, at https://bitfocus.io
